STOCKS = [
    {"symbol": "RELIANCE.NS", "name": "Reliance Industries", "sector": "Energy", "industry": "Integrated Oil & Gas"},
    {"symbol": "TCS.NS", "name": "Tata Consultancy Services", "sector": "Technology", "industry": "IT Services"},
    {"symbol": "INFY.NS", "name": "Infosys", "sector": "Technology", "industry": "IT Services"},
    {"symbol": "HDFCBANK.NS", "name": "HDFC Bank", "sector": "Financial", "industry": "Banks"},
    {"symbol": "ICICIBANK.NS", "name": "ICICI Bank", "sector": "Financial", "industry": "Banks"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever", "sector": "Consumer", "industry": "Food & Beverage"},
    {"symbol": "LT.NS", "name": "Larsen & Toubro", "sector": "Industrial", "industry": "Engineering & Construction"},
    {"symbol": "AXISBANK.NS", "name": "Axis Bank", "sector": "Financial", "industry": "Banks"},
    {"symbol": "SBIN.NS", "name": "State Bank of India", "sector": "Financial", "industry": "Banks"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel", "sector": "Communication", "industry": "Telecom"},
    {"symbol": "ITC.NS", "name": "ITC", "sector": "Consumer", "industry": "Tobacco"},
    {"symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank", "sector": "Financial", "industry": "Banks"},
    {"symbol": "MARUTI.NS", "name": "Maruti Suzuki", "sector": "Consumer", "industry": "Auto Manufacturers"},
    {"symbol": "ONGC.NS", "name": "Oil & Natural Gas Corporation", "sector": "Energy", "industry": "Oil & Gas"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance", "sector": "Financial", "industry": "Consumer Finance"},
    {"symbol": "HDFCLIFE.NS", "name": "HDFC Life Insurance", "sector": "Financial", "industry": "Life Insurance"},
    {"symbol": "SUNPHARMA.NS", "name": "Sun Pharmaceutical", "sector": "Healthcare", "industry": "Pharmaceuticals"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints", "sector": "Consumer", "industry": "Household Products"},
    {"symbol": "TITAN.NS", "name": "Titan Company", "sector": "Consumer", "industry": "Apparel"},
    {"symbol": "UPL.NS", "name": "UPL Limited", "sector": "Basic Materials", "industry": "Chemicals"},
]
